### PR TITLE
Add playwright commands

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
I have some issues with 

```sh
cliferay playwright test -- -g "grep with multiple words"
```

Because `brashly` tries to normalize the stuff after `--`, I think it is fixed here: https://github.com/DannyBen/bashly/pull/511.

Maybe we can try to update `bashly`  :D

**Comment by 4lejandrito** [comment]
I've updated bashly in master. Can you rebase and try again?

**Comment by boton** [comment]
It isn't working with multiple words :( 
image

**Comment by boton** [comment]
It was rebased but I have the same problem :(

**Comment by 4lejandrito** [comment]
I added playwright installation on build https://github.com/4lejandrito/cliferay/commit/86626b8367f938d9fea362a1a51a9bae1aee0422. For the other commands I think we can do nothing for now :( I am closing this.

**Pull request closed without merging**
